name: CI01
permissions:
  contents: write

on: 
  workflow_dispatch:
    inputs:
      release:
        description: "Publish a release"
        required: false
        default: true
        type: boolean

env:
  CI_CHUNK_SIZE: 65

jobs:
  build_individual:
    name: Build individual modules (Only Wnacg)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Prepare signing key
        run: |
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > signingkey.jks
      - name: Build extensions (Only Wnacg Source)
        env:
          CI_CHUNK_NUM: 0
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          chmod +x ./gradlew | true
          # 仅编译 src/wnacg 单个模块
          ./gradlew -p src/wnacg assembleRelease
      - name: Upload Wnacg build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "individual-apks"
          path: |
            src/wnacg/build/outputs/apk/release/*.apk
            src/wnacg/build/outputs/jar/release/*.jar
            **/keiyoushi-source-info.json
          retention-days: 1

      - name: Clean up signing key
        if: always()
        run: rm -f $GITHUB_WORKSPACE/signingkey.jks

  publish_repo:
    name: Publish repo
    if: ${{ inputs.release == true }}
    needs:
      - build_individual
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifacts
        uses: actions/download-artifact@v8
        with:
          path: ~/apk-artifacts

      - name: Checkout main branch
        uses: actions/checkout@v7
        with:
          ref: main
          path: main
          persist-credentials: false

      - name: Checkout repo branch
        uses: actions/checkout@v7
        with:
          ref: repo
          path: repo
          persist-credentials: true

      # 修复之前 logs.txt 不存在导致的 Git exit code 128 报错
      - name: Precreate log directory & empty log file
        run: |
          cd repo
          mkdir -p src/zh
          touch src/zh/logs.txt
          ls -la src/zh

      - name: Publish and deploy repo
        env:
          DELETE: '["zh.copymangas"]'
        run: |
          cd repo
          pip install protobuf
          python ../main/.github/scripts/publish-repo.py "$DELETE"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git status
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update extensions repo (only Wnacg)"
            git push
          else
            echo "No changes to commit"
          fi
